# Change these first
owner: Rileyjrjohns # Your GitHub organization or username, where this repository lives
repo: vibly-status # The name of this repository
sites:
  - name: Serveur
    url: https://rest.vibly.app
  - name: Site Internet
    url: https://vibly.fr
  - name: CDN utilisateurs
    url: https://user-cdn.vibly.app/health.html
  - name: CDN évènements
    url: https://events-cdn.vibly.app/health.html
  - name: CDN associations
    url: https://unions-cdn.vibly.app/health.html
  - name: CDN documents
    url: https://legal-cdn.vibly.app/health.html
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vibly.app
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Rileyjrjohns/vibly-status/2f7345a3cb2bbc1f967310601cf7f0935499f24e/assets/vibly_logo.svg
  name: Vibly Status
  introTitle: "Suivi en temps réel de la disponibilité des services Vibly"
  introMessage: Cette page de suivi de status indique l'état de nos services en temps réel.
  navbar:
    - title: Status
      href: /
i18n:
  activeIncidents: Incidents actifs
  allSystemsOperational: Tous les systèmes sont opérationnels
  incidentReport: "Rapport de l'incident #$NUMBER →"
  activeIncidentSummary: Ouvert le $DATE avec $POSTS publications
  incidentTitle: Details de l'incident $NUMBER 
  incidentDetails: Détails de l'incident
  incidentFixed: Corrigé
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert le
  incidentClosedAt: Fermé le
  incidentViewOnGitHub: Voir et s'abonner sur GitHub
  incidentCommentSummary: Posté le $DATE par $AUTHOR
  incidentBack: ← Retour à tous les incidents
  pastIncidents: Incidents passés
  pastIncidentsResolved: Résolu en $MINUTES minutes avec $POSTS publications
  liveStatus: Status en temps réel
  overallUptime: "Temps de fonctionnement global : $UPTIME"
  overallUptimeTitle: Temps de fonctionnement global
  averageResponseTime: "Temps de réponse moyen : $TIMEms"
  averageResponseTimeTitle: Réponse moyenne
  sevelDayResponseTime: Délai de réponse les 7 derniers jours
  responseTimeMs: Temps de réponse (ms)
  up: En ligne
  down: Hors ligne
  degraded: Dégradé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Limite de débit dépassée
  rateLimitExceededIntro: Vous avez dépassé le nombre de requêtes que vous pouvez effectuer en une heure. Vous devrez donc attendre avant d'accéder à nouveau à ce site Web. Vous pouvez également ajouter un jeton d'accès personnel GitHub pour continuer à utiliser ce site Web.
  rateLimitExceededWhatDoesErrorMean: Que signifie cette erreur ?
  rateLimitExceededErrorMeaning: Ce site web utilise l'API GitHub pour accéder à des données en temps réel sur l'état de nos sites web. Par défaut, GitHub autorise à chaque adresse IP 60 requêtes par heure, que vous avez consommées.
  rateLimitExceededErrorHowCanFix: Comment puis-je le réparer ?
  rateLimitExceededErrorFix: Vous pouvez attendre une heure de plus et la limite de votre adresse IP sera rétablie. Vous pouvez également ajouter votre jeton d'accès personnel GitHub, qui vous donne droit à 5 000 demandes supplémentaires par heure.
  rateLimitExceededGeneratePAT: Apprenez comment générer un jeton d'accès personnel
  rateLimitExceededHasSet: Vous avez défini un jeton d'accès personnel.
  rateLimitExceededRemoveToken: Retirer le jeton
  rateLimitExceededGitHubPAT: Token d'accès personnel GitHub
  rateLimitExceededCopyPastePAT: Copiez et collez votre jeton
  rateLimitExceededSaveToken: Sauvegarder le jeton
  errorTitle: Une erreur s'est produite
  errorIntro: Une erreur s'est produite en essayant d'obtenir les derniers détails du statut.
  errorText: Vous pourrez réessayer dans quelques instants.
  errorHome: Aller à la page d'accueil
  pastScheduledMaintenance: Entretien programmé passé
  scheduledMaintenance: Maintenance programmée
  scheduledMaintenanceSummaryStarted: Démarré le $DATE pour $DURATION minutes
  scheduledMaintenanceSummaryStarts: Commence le $DATE pour $DURATION minutes
  startedAt: Commencé le
  startsAt: Commence le
  duration: Durée
  durationMin: $DURATION minutes
  incidentCompleted: Terminé
  incidentScheduled: Programmé

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
